# Assignment:3

##Q1. Creating and Inspecting DataFrames

In [11]:
import pandas as pd
data={
    'name':['neel','viraj','krushna','chirag','harsh'],
    'age':[20,22,21,22,23],
    'city':['ahmedabad','surat','bhavnagar','baroda','ahmedabad']
}
df=pd.DataFrame(data)
df.to_csv('students.csv', index=False)

In [12]:
df=pd.read_csv('students.csv')
print(df)

      name  age       city
0     neel   20  ahmedabad
1    viraj   22      surat
2  krushna   21  bhavnagar
3   chirag   22     baroda
4    harsh   23  ahmedabad

In [13]:
print(df.shape)

(5, 3)

In [21]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [15]:
print(df.dtypes)

name    object
age      int64
city    object
dtype: object

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   city    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [22]:
df.describe()

             age
count   5.000000
mean   21.600000
std     1.140175
min    20.000000
25%    21.000000
50%    22.000000
75%    22.000000
max    23.000000

In [23]:
df.head(3)

      name  age       city
0     neel   20  ahmedabad
1    viraj   22      surat
2  krushna   21  bhavnagar

In [24]:
df.tail(2)

     name  age       city
3  chirag   22     baroda
4   harsh   23  ahmedabad

##Q2. Data Selection and Indexing

In [25]:
df = pd.DataFrame({
'A': [10, 20, 30, 40, 50],
'B': [15, 25, 35, 45, 55],
'C': ['x', 'y', 'z', 'x', 'y']
}, index=['r1', 'r2', 'r3', 'r4', 'r5'])
df.to_csv('matrix_data.csv')
df = pd.read_csv('matrix_data.csv', index_col=0)

In [26]:
df['A']

r1    10
r2    20
r3    30
r4    40
r5    50
Name: A, dtype: int64

In [27]:
df[['A','B']]

     A   B
r1  10  15
r2  20  25
r3  30  35
r4  40  45
r5  50  55

In [29]:
df.loc['r3']

A    30
B    35
C     z
Name: r3, dtype: object

In [34]:
df.iloc[2]

A    30
B    35
C     z
Name: r3, dtype: object

In [36]:
df.loc['r3','B']

np.int64(35)

In [37]:
df.loc['r2':'r4','A':'B']

     A   B
r2  20  25
r3  30  35
r4  40  45

In [38]:
df.iloc[1:4, 0:2]

     A   B
r2  20  25
r3  30  35
r4  40  45

In [42]:
df.loc[df['A']>25]

     A   B  C
r3  30  35  z
r4  40  45  x
r5  50  55  y

In [43]:
df.loc[df['C'].isin(['x','z'])]

     A   B  C
r1  10  15  x
r3  30  35  z
r4  40  45  x

In [44]:
df.loc[df['B'].between(20,45)]

     A   B  C
r2  20  25  y
r3  30  35  z
r4  40  45  x

##Q3. Handling Missing Data

In [45]:
import numpy as np
df = pd.DataFrame({
'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
'Age': [20, np.nan, 21, 23, np.nan, 22],
'Marks': [85, 78, np.nan, 88, 75, np.nan],
'Subject': ['Math', 'Science', 'Math', np.nan, 'Math', 'Science']
})
df.to_csv('missing_data.csv', index=False)
df = pd.read_csv('missing_data.csv')

In [47]:
mask=df.isnull()
print(mask)

    Name    Age  Marks  Subject
0  False  False  False    False
1  False   True  False    False
2  False  False   True    False
3  False  False  False     True
4  False   True  False    False
5  False  False   True    False

In [51]:
nullsum=mask.sum()
print(nullsum)
print()
print(df.isnull().sum())

Name       0
Age        2
Marks      2
Subject    1
dtype: int64

Name       0
Age        2
Marks      2
Subject    1
dtype: int64

In [52]:
totalnull=nullsum.sum()
print(totalnull)
print()
print(df.isnull().sum().sum())

5

5

In [53]:
df.dropna()

    Name   Age  Marks Subject
0  Alice  20.0   85.0    Math

In [54]:
df.dropna(how='all')

      Name   Age  Marks  Subject
0    Alice  20.0   85.0     Math
1      Bob   NaN   78.0  Science
2  Charlie  21.0    NaN     Math
3    Diana  23.0   88.0      NaN
4      Eve   NaN   75.0     Math
5    Frank  22.0    NaN  Science

In [57]:
mean=df['Age'].mean()
print(mean)
df['Age'].fillna(mean )

21.5

0    20.0
1    21.5
2    21.0
3    23.0
4    21.5
5    22.0
Name: Age, dtype: float64

In [61]:
median=df['Marks'].median()
print(median)
print()
df['Marks'].fillna(median)

81.5

0    85.0
1    78.0
2    81.5
3    88.0
4    75.0
5    81.5
Name: Marks, dtype: float64

In [62]:
mode=df['Subject'].mode()
print(mode)
print()
df['Subject'].fillna(mode[0])

0    Math
Name: Subject, dtype: object

0       Math
1    Science
2       Math
3       Math
4       Math
5    Science
Name: Subject, dtype: object

dropna() method is used to drop the rows which containd missing values while the fillna() method id used to fill particlar value where the value is missing.

##Q4. Data Cleaning: Duplicates, Types, and Renaming

In [123]:
df = pd.DataFrame({
'Student_ID': ['S001', 'S002', 'S003', 'S001', 'S004', 'S002'],
'Join_Date': ['2023-01-15', '2023-02-20', '2023-03-10',
'2023-01-15', '2023-04-05', '2023-02-20'],
'Score': ['85.5', '78.0', '92.3', '85.5', '88.1', '78.0'],
'Passed': ['Yes', 'No', 'Yes', 'Yes', 'Yes', 'No']
})
df.to_csv('cleaning_data.csv', index=False)
df = pd.read_csv('cleaning_data.csv')

In [124]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [125]:
df.duplicated().sum()

np.int64(2)

In [126]:
unique=df.drop_duplicates()
print(df)
unique

  Student_ID   Join_Date  Score Passed
0       S001  2023-01-15   85.5    Yes
1       S002  2023-02-20   78.0     No
2       S003  2023-03-10   92.3    Yes
3       S001  2023-01-15   85.5    Yes
4       S004  2023-04-05   88.1    Yes
5       S002  2023-02-20   78.0     No

  Student_ID   Join_Date  Score Passed
0       S001  2023-01-15   85.5    Yes
1       S002  2023-02-20   78.0     No
2       S003  2023-03-10   92.3    Yes
4       S004  2023-04-05   88.1    Yes

In [127]:
df['Score']=df['Score'].astype(float)
df

  Student_ID   Join_Date  Score Passed
0       S001  2023-01-15   85.5    Yes
1       S002  2023-02-20   78.0     No
2       S003  2023-03-10   92.3    Yes
3       S001  2023-01-15   85.5    Yes
4       S004  2023-04-05   88.1    Yes
5       S002  2023-02-20   78.0     No

In [128]:
df['Join_Date']=pd.to_datetime(df['Join_Date'])
df

  Student_ID  Join_Date  Score Passed
0       S001 2023-01-15   85.5    Yes
1       S002 2023-02-20   78.0     No
2       S003 2023-03-10   92.3    Yes
3       S001 2023-01-15   85.5    Yes
4       S004 2023-04-05   88.1    Yes
5       S002 2023-02-20   78.0     No

In [129]:
df["Passed"] = df["Passed"].map({"Yes": True, "No": False})

In [130]:
df

  Student_ID  Join_Date  Score  Passed
0       S001 2023-01-15   85.5    True
1       S002 2023-02-20   78.0   False
2       S003 2023-03-10   92.3    True
3       S001 2023-01-15   85.5    True
4       S004 2023-04-05   88.1    True
5       S002 2023-02-20   78.0   False

In [131]:
df = df.rename(columns={'Student_ID': 'ID', 'Join_Date': 'Enrollment_Date'})

df

     ID Enrollment_Date  Score  Passed
0  S001      2023-01-15   85.5    True
1  S002      2023-02-20   78.0   False
2  S003      2023-03-10   92.3    True
3  S001      2023-01-15   85.5    True
4  S004      2023-04-05   88.1    True
5  S002      2023-02-20   78.0   False

In [133]:
df=df.replace(True,"1")
df=df.replace(False,"0")
df['Passed']=df['Passed'].astype(np.int32)
df['Passed']

0    1
1    0
2    1
3    1
4    1
5    0
Name: Passed, dtype: int32

Data type conversion is important because statistical calculations need data to be in the correct format. It helps avoid errors and makes sure the results of the analysis are accurate and meaningful.

##Q5. Sorting and Ranking

In [134]:
df = pd.DataFrame({
'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
'Marks': [85, 78, 92, 88, 75, 91],
'Attendance': [90, 85, 95, 80, 88, 92]
})
df.to_csv('sorting_data.csv', index=False)
df = pd.read_csv('sorting_data.csv')

In [137]:
ascending = df.sort_values('Marks', ascending=True)
print(ascending)

      Name  Marks  Attendance
4      Eve     75          88
1      Bob     78          85
0    Alice     85          90
3    Diana     88          80
5    Frank     91          92
2  Charlie     92          95

In [138]:
descending = df.sort_values('Marks', ascending=False)
print(descending)

      Name  Marks  Attendance
2  Charlie     92          95
5    Frank     91          92
3    Diana     88          80
0    Alice     85          90
1      Bob     78          85
4      Eve     75          88

In [139]:
multi = df.sort_values(
    by=['Attendance', 'Marks'],
    ascending=[True, False]
)
print(multi)

      Name  Marks  Attendance
3    Diana     88          80
1      Bob     78          85
4      Eve     75          88
0    Alice     85          90
5    Frank     91          92
2  Charlie     92          95

In [140]:
df['Rank'] = df['Marks'].rank(
    method='min',
    ascending=False
)

print(df)

      Name  Marks  Attendance  Rank
0    Alice     85          90   4.0
1      Bob     78          85   5.0
2  Charlie     92          95   1.0
3    Diana     88          80   3.0
4      Eve     75          88   6.0
5    Frank     91          92   2.0

In [142]:
df['AttendanceRank'] = df['Attendance'].rank(
    method='dense',
    ascending=False
)

print(df)

      Name  Marks  Attendance  Rank  AttendanceRank
0    Alice     85          90   4.0             3.0
1      Bob     78          85   5.0             5.0
2  Charlie     92          95   1.0             1.0
3    Diana     88          80   3.0             6.0
4      Eve     75          88   6.0             4.0
5    Frank     91          92   2.0             2.0

In [143]:
top3 = df.nlargest(3, 'Marks')
print(top3)

      Name  Marks  Attendance  Rank  AttendanceRank
2  Charlie     92          95   1.0             1.0
5    Frank     91          92   2.0             2.0
3    Diana     88          80   3.0             6.0

In [144]:
last2 = df.nsmallest(2, 'Attendance')
print(last2)

    Name  Marks  Attendance  Rank  AttendanceRank
3  Diana     88          80   3.0             6.0
1    Bob     78          85   5.0             5.0

In [145]:
df = df.sort_values('Marks', ascending=False)
df = df.reset_index(drop=True)
print(df)

      Name  Marks  Attendance  Rank  AttendanceRank
0  Charlie     92          95   1.0             1.0
1    Frank     91          92   2.0             2.0
2    Diana     88          80   3.0             6.0
3    Alice     85          90   4.0             3.0
4      Bob     78          85   5.0             5.0
5      Eve     75          88   6.0             4.0

##Q6. GroupBy Operations

In [147]:
df = pd.DataFrame({
'Department': ['Sales', 'IT', 'Sales', 'HR', 'IT', 'HR', 'Sales', 'IT'],
'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry'],
'Salary': [50000, 70000, 55000, 45000, 75000, 48000, 60000, 72000],
'Experience': [2, 5, 3, 4, 6, 3, 4, 7]
})
df.to_csv('employee_data.csv', index=False)
df = pd.read_csv('employee_data.csv')

In [148]:
mean = df.groupby('Department')['Salary'].mean()
print(mean)

Department
HR       46500.000000
IT       72333.333333
Sales    55000.000000
Name: Salary, dtype: float64

In [149]:
totalsalary = df.groupby('Department')['Salary'].sum()
print(totalsalary)

Department
HR        93000
IT       217000
Sales    165000
Name: Salary, dtype: int64

In [150]:
employeecount = df.groupby('Department').size()
print(employeecount)

Department
HR       2
IT       3
Sales    3
dtype: int64

In [151]:
exp = df.groupby('Department')['Experience'].agg(['min', 'max', 'mean'])
print(exp)

            min  max  mean
Department
HR            3    4   3.5
IT            5    7   6.0
Sales         2    4   3.0

In [152]:
dept = df.groupby('Department').agg({
    'Salary': 'mean',
    'Experience': 'sum'
})
print(dept)

                  Salary  Experience
Department
HR          46500.000000           7
IT          72333.333333          18
Sales       55000.000000           9

In [153]:
df['Dept_Avg_Salary'] = df.groupby('Department')['Salary'].transform('mean')
print(df)

  Department Employee  Salary  Experience  Dept_Avg_Salary
0      Sales    Alice   50000           2     55000.000000
1         IT      Bob   70000           5     72333.333333
2      Sales  Charlie   55000           3     55000.000000
3         HR    Diana   45000           4     46500.000000
4         IT      Eve   75000           6     72333.333333
5         HR    Frank   48000           3     46500.000000
6      Sales    Grace   60000           4     55000.000000
7         IT    Henry   72000           7     72333.333333

In [154]:
deptavg = df.groupby('Department')['Salary'].mean()
filtered_departments = deptavg[deptavg > 55000]
print(filtered_departments)

Department
IT    72333.333333
Name: Salary, dtype: float64

agg() reduces each group to a summary value, such as one mean salary per department. transform() calculates something for each group but returns the result with the same number of rows as the original DataFrame, so it can be added back as a column.

##Q7. Statistical Analysis and Value Counts

In [155]:
df = pd.DataFrame({
'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A'],
'Sales': [120, 200, 150, 180, 220, 130, 190, 210, 160, 175],
'Rating': [4.2, 3.8, 4.5, 4.0, 3.9, 4.3, 4.1, 4.0, 4.4, 3.7],
'Region': ['East', 'West', 'East', 'North', 'West', 'South',
'East', 'West', 'South', 'North']
})
df.to_csv('product_data.csv', index=False)
df = pd.read_csv('product_data.csv')

In [159]:
print("Sales Mean:", df['Sales'].mean())
print("Sales Median:", df['Sales'].median())
print("Sales Standard Deviation:", df['Sales'].std())


print("Rating Mean:", df['Rating'].mean())
print("Rating Median:", df['Rating'].median())
print("Rating Standard Deviation:", df['Rating'].std())


print("Minimum Sales:", df['Sales'].min())
print("Maximum Sales:", df['Sales'].max())


print(df['Sales'].quantile([0.25, 0.50, 0.75]))


correlation = df[['Sales', 'Rating']].corr()
print(correlation)




covariance = df[['Sales', 'Rating']].cov()
print(covariance)


print(df['Product'].value_counts())


print(df['Region'].value_counts(normalize=True) * 100)

print(df.nunique())


range = df['Sales'].max() - df['Sales'].min()
print("Sales Range:", range)

Sales Mean: 173.5

Sales Median: 177.5
Sales Standard Deviation: 33.33749973961588
Rating Mean: 4.09
Rating Median: 4.05
Rating Standard Deviation: 0.2601281735350223
Minimum Sales: 120
Maximum Sales: 220
0.25    152.5
0.50    177.5
0.75    197.5
Name: Sales, dtype: float64
           Sales    Rating
Sales   1.000000 -0.636145
Rating -0.636145  1.000000
              Sales    Rating
Sales   1111.388889 -5.516667
Rating    -5.516667  0.067667
Product
A    4
B    3
C    3
Name: count, dtype: int64
Region
East     30.0
West     30.0
North    20.0
South    20.0
Name: proportion, dtype: float64
Product     3
Sales      10
Rating      9
Region      4
dtype: int64
Sales Range: 100

##Q8. Data Transformation: Apply, Map, and Replace

In [160]:
df = pd.DataFrame({
'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
'Marks': [85, 78, 92, 88, 75],
'Grade_Letter': ['B', 'C', 'A', 'A', 'C']
})
df.to_csv('grades_data.csv', index=False)
df = pd.read_csv('grades_data.csv')

In [163]:

df['Marks_Squared'] = df['Marks'].apply(lambda x: x**2)
print(df)

      Name  Marks Grade_Letter  Marks_Squared
0    Alice     85            B           7225
1      Bob     78            C           6084
2  Charlie     92            A           8464
3    Diana     88            A           7744
4      Eve     75            C           5625

In [164]:
df['Category'] = df['Marks'].apply(
    lambda x: 'High' if x >= 85
    else 'Medium' if x >= 70
    else 'Low'
)
print(df)

      Name  Marks Grade_Letter  Marks_Squared Category
0    Alice     85            B           7225     High
1      Bob     78            C           6084   Medium
2  Charlie     92            A           8464     High
3    Diana     88            A           7744     High
4      Eve     75            C           5625   Medium

In [165]:
grade_map = {
    'A': 4,
    'B': 3,
    'C': 2,
    'D': 1,
    'F': 0
}

df['Grade_Points'] = df['Grade_Letter'].map(grade_map)
print(df)

      Name  Marks Grade_Letter  Marks_Squared Category  Grade_Points
0    Alice     85            B           7225     High             3
1      Bob     78            C           6084   Medium             2
2  Charlie     92            A           8464     High             4
3    Diana     88            A           7744     High             4
4      Eve     75            C           5625   Medium             2

In [166]:
df['Name'] = df['Name'].replace('Charlie', 'Chris')
print(df)

    Name  Marks Grade_Letter  Marks_Squared Category  Grade_Points
0  Alice     85            B           7225     High             3
1    Bob     78            C           6084   Medium             2
2  Chris     92            A           8464     High             4
3  Diana     88            A           7744     High             4
4    Eve     75            C           5625   Medium             2

In [167]:
df = df.apply(
    lambda column: column.map(
        lambda x: x.upper() if isinstance(x, str) else x
    )
)
print(df)

    Name  Marks Grade_Letter  Marks_Squared Category  Grade_Points
0  ALICE     85            B           7225     HIGH             3
1    BOB     78            C           6084   MEDIUM             2
2  CHRIS     92            A           8464     HIGH             4
3  DIANA     88            A           7744     HIGH             4
4    EVE     75            C           5625   MEDIUM             2

apply() is mainly used on a Series or DataFrame when you want to apply a function to values, rows, or columns. map() is used on a Series to transform individual values, while applymap() was used to apply a function to every individual cell of a DataFrame; in newer Pandas versions, DataFrame.map() is used instead of applymap()

##Q9. Merging, Joining, and Concatenating

In [168]:
df1 = pd.DataFrame({
'ID': [1, 2, 3, 4],
'Name': ['Alice', 'Bob', 'Charlie', 'Diana']
})
df1.to_csv('employees.csv', index=False)
df2 = pd.DataFrame({
'ID': [3, 4, 5, 6],
'Salary': [50000, 60000, 70000, 80000]
})
df2.to_csv('salaries.csv', index=False)
df3 = pd.DataFrame({
'ID': [7, 8],
'Name': ['Eve', 'Frank'],
'Salary': [55000, 65000]
})
df3.to_csv('new_employees.csv', index=False)
df1 = pd.read_csv('employees.csv')
df2 = pd.read_csv('salaries.csv')
df3 = pd.read_csv('new_employees.csv')

In [169]:
inner = pd.merge(df1, df2, on='ID', how='inner')
print("Inner Join:")
print(inner)
print("Rows:", len(inner))

Inner Join:
   ID     Name  Salary
0   3  Charlie   50000
1   4    Diana   60000
Rows: 2

In [170]:
left = pd.merge(df1, df2, on='ID', how='left')
print("\nLeft Join:")
print(left)

Left Join:
   ID     Name   Salary
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie  50000.0
3   4    Diana  60000.0

In [171]:
right = pd.merge(df1, df2, on='ID', how='right')
print("\nRight Join:")
print(right)

Right Join:
   ID     Name  Salary
0   3  Charlie   50000
1   4    Diana   60000
2   5      NaN   70000
3   6      NaN   80000

In [172]:
outer = pd.merge(df1, df2, on='ID', how='outer')
print("\nOuter Join:")
print(outer)
print("Rows:", len(outer))

Outer Join:
   ID     Name   Salary
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie  50000.0
3   4    Diana  60000.0
4   5      NaN  70000.0
5   6      NaN  80000.0
Rows: 6

In [173]:
vertical = pd.concat([df1, df3], axis=0)
print("\nVertical Concatenation:")
print(vertical)

Vertical Concatenation:
   ID     Name   Salary
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie      NaN
3   4    Diana      NaN
0   7      Eve  55000.0
1   8    Frank  65000.0

In [174]:
horizontal = pd.concat([df1, df2], axis=1)
print("\nHorizontal Concatenation:")
print(horizontal)

Horizontal Concatenation:
   ID     Name  ID  Salary
0   1    Alice   3   50000
1   2      Bob   4   60000
2   3  Charlie   5   70000
3   4    Diana   6   80000

merge() is used when you want to combine DataFrames based on a common column or key, such as ID. concat() is used to simply join DataFrames together row-wise or column-wise, usually when their structure is compatible.

Use an inner join when you only want records that exist in both datasets and are interested in their common information. Use an outer join during EDA when you want to see all records and identify missing matches, which is useful for finding data-quality or missing-data problems

##Q10. Pivot Tables and Cross Tabulation

In [175]:
df = pd.DataFrame({
'Region': ['North', 'South', 'East', 'West', 'North',
'South', 'East', 'West', 'North', 'South'],
'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'B', 'A'],
'Sales': [200, 150, 300, 250, 180, 220, 280, 260, 190, 210],
'Profit': [50, 30, 80, 60, 45, 55, 70, 65, 40, 52]
})
df.to_csv('sales_data.csv', index=False)
df = pd.read_csv('sales_data.csv')

In [176]:
pivot_sales = pd.pivot_table(
    df,
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='mean'
)

print(pivot_sales)

Product      A      B
Region
East     280.0  300.0
North    190.0  190.0
South    180.0  220.0
West       NaN  255.0

In [177]:
pivot_profit = pd.pivot_table(
    df,
    values='Profit',
    index='Region',
    columns='Product',
    aggfunc='sum'
)

print(pivot_profit)

Product     A      B
Region
East     70.0   80.0
North    95.0   40.0
South    82.0   55.0
West      NaN  125.0

In [178]:
pivot_multiple = pd.pivot_table(
    df,
    values=['Sales', 'Profit'],
    index='Region',
    aggfunc={
        'Sales': 'mean',
        'Profit': 'sum'
    }
)

print(pivot_multiple)

        Profit       Sales
Region
East       150  290.000000
North      135  190.000000
South      137  193.333333
West       125  255.000000

In [179]:
cross_count = pd.crosstab(
    df['Region'],
    df['Product']
)

print(cross_count)

Product  A  B
Region
East     1  1
North    2  1
South    2  1
West     0  2

In [180]:
cross_proportion = pd.crosstab(
    df['Region'],
    df['Product'],
    normalize=True
)

print(cross_proportion)

Product    A    B
Region
East     0.1  0.1
North    0.2  0.1
South    0.2  0.1
West     0.0  0.2

In [181]:
cross_margin = pd.crosstab(
    df['Region'],
    df['Product'],
    margins=True
)

print(cross_margin)

Product  A  B  All
Region
East     1  1    2
North    2  1    3
South    2  1    3
West     0  2    2
All      5  5   10

groupby() is useful when you mainly want to calculate summaries for groups. pivot_table() is more useful in EDA when you want to see relationships between two or more categorical variables in a table format, making comparisons easier.

A pivot table is mainly used to summarize numerical data using functions like mean, sum, or count. A crosstab is mainly used to show the frequency or proportion of combinations between categorical variables, such as how many Product A and Product B records exist in each Region.